### ISSUE TITLE
feat: More Hub network tests

### ISSUE THREAD

**Issue by sagar-a16z** [farcasterxyz/hubble#129]
**What is the feature you would like to implement?**
We need to be able to simulate a network of Hubs and try to emulate real networks

**Why is this feature important?**
The following test cases are not met 

- [ ] Network partitions
- [ ] Network throughput
- [ ] Network health in adversarial conditions
- [ ] Lossy networks
- [ ] Simple Sync between multiple Hubs 
- [ ] Hub disconnect and reconnect

**Will the protocol spec need to be updated??**
No

**How should this feature be built? (optional)**
Need to expand on the existing tests in the tree and build test specific tooling for them

**Comment by adityapk00** [comment]
Most of these are implemented, except the throughput, which is being tracked with the benchmark tests
