### ISSUE TITLE
feat: EthEventsProvider should injest event logs in batches.

### ISSUE THREAD

**Issue by adityapk00** [farcasterxyz/hubble#317]
**What is the feature you would like to implement?**
When the `EthEventsProvider` (https://github.com/farcasterxyz/hub/blob/main/src/storage/engine/flatbuffers/providers/ethEventsProvider.ts) is first created, it connects to an Ethereum RPC node and injests historical logs. 

Right now, it just gets all logs since the start in one go, but it should probably be fetched in batches of ~10k blocks.

**Why is this feature important?**
As more blocks pass, the chances of timeouts and other errors increases. We should batch the incoming logs to make them easier to be processed. 

**How should this feature be built? (optional)**
* Add a way to batch the calls to `getHistoricalIdEvents` (https://github.com/farcasterxyz/hub/blob/main/src/storage/engine/flatbuffers/providers/ethEventsProvider.ts#L196)
* Add a way to batch the calls to `getHistoricalNameEvents` (https://github.com/farcasterxyz/hub/blob/main/src/storage/engine/flatbuffers/providers/ethEventsProvider.ts#L229)

**Additional context**
Bonus - Add retry logic for failed blocks

**Comment by Rnamita** [comment]
I would be interested in taking this up!

**Comment by varunsrin** [comment]
all yours!

**Comment by Rnamita** [comment]
Looking at recent commits, I assume the file ethEventsProvider.test.ts has been moved from src/storage/engine/flatbuffers/providers/ethEventsProvider.ts to src/eth/ethEventsProvider.test.ts. Also the getHistoricalIdEvents has been renamed to syncHistoricalIdEvents and getHistoricalNameEvents to syncHistoricalNameEvents. In this case can I please get the reference to the updated code so that It'll be easier for me to work on this. Thanks! :)

**Comment by adityapk00** [comment]
You are right, the code has moved a bit. 

The functions are now: 
https://github.com/farcasterxyz/hub/blob/main/src/eth/ethEventsProvider.ts#L195

and 
https://github.com/farcasterxyz/hub/blob/main/src/eth/ethEventsProvider.ts#L228

**Comment by Rnamita** [comment]
Sorry missed the reference to the code again due to migration, can you please redirect me again to the same :)

**Comment by Rnamita** [comment]
ping! would be glad if I could be redirected to the updated code. thanks ! :)

**Comment by varunsrin** [comment]
@Rnamita can you try searching for the file by name? i don't think that has changed

**Comment by Rnamita** [comment]
yeah I figured it is https://github.com/farcasterxyz/hub/blob/main/apps/hub/src/eth/ethEventsProvider.ts but couldn't navigate the exact functions, are they syncHistoricalIdEvents and syncHistoricalIdEvents

**Comment by varunsrin** [comment]
@Rnamita if youre having trouble with this ticket, i'd suggest starting with another ticket to get oriented with the codebase like [this one](https://github.com/farcasterxyz/hubble/issues/344)

**Comment by Rnamita** [comment]
sure @varunsrin, I think that would be a good starting point!
