### ISSUE TITLE
chore: upgrade libp2p to latest 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#329]
**What is the feature you would like to implement?**

Upgrade all the libp2p dependencies to the latest, fix any issues that crop up and run a peer to peer test to ensure that they are all working. This ticket is dependent on us reinstating `yarn bench` or a similar test suite to ensure that things work end to end again after the upgrade.

**Comment by adaddeo** [comment]
Is there an issue or more info on the `yarn bench` dependency? could work on this + that

**Comment by varunsrin** [comment]
i think @sagar-a16z is going to have something out this week, so this should be ready to go next week
