### ISSUE TITLE
chore: test flatbuffer schemas with different languages

### ISSUE THREAD

**Issue by pfletcherhill** [farcasterxyz/hubble#351]
We've only generated typescript code to interact with our flatbuffer schemas. Since we can reasonably expect devs to implement hubs or clients in different languages, we should confirm our flatbuffer schemas work as expected in those other languages as well.

**Comment by varunsrin** [comment]
@pfletcherhill we should update this ticket to just test out rust. the goal would be to: 

1. generate a bunch of flatbuffers in typescript
2. export the data as bytes
3. import using rust flatbuffers and turn them into objects
4. validate that the objects are structured correctly

might be nice to have it as a ci/cd loop for the package too

**Comment by varunsrin** [comment]
Wrote a simple rust program today to produce the a flatbuffer that was then read into typescript codebase and run through  `validations.validateMessage` successfully. 

@pfletcherhill we should discuss what other checks need to be performed to ensure that the message was produced correctly

**Comment by pfletcherhill** [comment]
Closing due to protobuf migration
