### ISSUE TITLE
feat: build messages from backend and send to hub

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#360]
Can use the `@farcaster/js` library to build messages and submit them. See example code here: https://github.com/farcasterxyz/hub/tree/main/packages/js

**Comment by varunsrin** [comment]
@sds and @adaddeo should we consider this closed? or is there more work to be done?

**Comment by sds** [comment]
I think we can close for the purposes of this ticket. There will be more nuance to how/when we publish messages (e.g. periodically vs at time of event) but all the plumbing is in place to consider this done.
