### ISSUE TITLE
chore: review message formats and names 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#58]
Once all changes are in and the release is ready to be cut, do another pass of all the message formats and names before finalizing them.

**Comment by pfletcherhill** [comment]
https://www.notion.so/farcasterxyz/v2-messages-format-review-83550a618ee1479d976f180b90f57790

**Comment by pfletcherhill** [comment]
https://github.com/farcasterxyz/hubble/blob/main/packages/protobufs/src/schemas/message.proto
