### ISSUE TITLE
feat: restricted peer list

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#583]
**What is the feature you would like to implement?**

Have a hardcoded list of peers that Hubble will listen to for updates by default. It's ok if we broadcast updates and respond to grpc calls from non-trusted peers, we just don't want to consume data from them. 

**Why is this feature important?**

In Phase III, we should only ingest messages from trusted peers and validate that things work correctly before opening up access.

**Will the protocol spec need to be updated??**

No

**Comment by varunsrin** [comment]
worth prioritizing this in phase 2, so that someone running a hub doesn't dump a bunch of data into one of our hubs and mess up our integrity checks that we will build in #584

**Comment by adityapk00** [comment]
Fixed in #595
