### ISSUE TITLE
feat: set up farcaster testnet and periodically publish messages to it

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#585]
**What is the feature you would like to implement?**
Operate a functional testnet with live data that can be used to test changes before they are made to production

**Why is this feature important?**
Provides a testing ground for developers to write and publish messages without having to rely on mainnet hubs. 

**Will the protocol spec need to be updated??**
No

**How should this feature be built? (optional)**

- Stand up a Hub instance in Warpcast's infrastructure configured to run on testnet
- Stand up a service that automatically publishes a message of every category to the hubs periodically

**Comment by payton** [comment]
Are there existing plans for isolated/local hubs, too?

Still ramping up on hubble / contributions here, but I would find it useful to run my own internal staging hub in addition to a public testnet being available.

1. Boot up anvil node
2. Deploy registry contracts
3. Boot up isolated hub pointed at local rpc endpoint
4. Publish seed data to anvil
5. Publish seed deltas to local hub (steps 4/5 w/ public anvil keypairs)

**Comment by varunsrin** [comment]
We would just need to allow configuring the contract address, which should be an easy addition. @adityapk00 wdyt?

**Comment by payton** [comment]
@varunsrin @adityapk00 happy to put up a diff if this is something that would be considered.

I think it makes sense to generalize `makeWithGoerli` into a factory that optionally accepts address overrides. 

Another option would be to allow abi overrides. This would future-proof things a bit more and allow folks to test out new id/name registry changes more easily (although this shouldn't change much).

https://github.com/farcasterxyz/hubble/blob/cf8624d3409b6a10f27e9e0bc2620a4e3d8c6689/apps/hubble/src/hubble.ts#L158-L164

https://github.com/farcasterxyz/hubble/blob/cf8624d3409b6a10f27e9e0bc2620a4e3d8c6689/apps/hubble/src/eth/ethEventsProvider.ts#L89-L108

**Comment by adityapk00** [comment]
Yes, that makes sense. Making the `makeWithGoerli` into a factory that can make out of any network is probably the right way to go. 

FWIW, the `cli.ts` already accepts `  .option('-f, --fir-address <address>', 'The address of the FIR contract')`, which allows overriding the contract, but we should generalize this into accepeting all the contract addresses needed.

**Comment by payton** [comment]
Sounds good. I'll get a diff out this evening or tomorrow morning.

**Comment by varunsrin** [comment]
@payton yes, would be very supportive of a PR. we would need to accept the fnr address over the command line and make sure that `makeWithGoerli` instantiates correctly when set up.

**Comment by payton** [comment]
> @payton yes, would be very supportive of a PR. we would need to accept the fnr address over the command line and make sure that `makeWithGoerli` instantiates correctly when set up.

@adityapk00 @varunsrin adding it here https://github.com/farcasterxyz/hubble/pull/623

**Comment by varunsrin** [comment]
@sds and @adityapk00 some open questions:

- Should this testnet be run against a testnet version of the contracts?
- How many hub instances should warpcast run to guarantee no data loss in case of failure?

**Comment by varunsrin** [comment]
from @adityapk00 

> I was thinking we’ll use the existing Goerli contracts, but with network=2 in the Hubs. 

> This way, people will be able to test against their actual FIDs, without needing to send new transactions to create new FIDs on a ethereum testnet

**Comment by varunsrin** [comment]
@adityapk00 i wonder if its good to create some friction here and actually have a separate set of contracts that people should be using for the test network. there are a couple of reasons for this: 

1. it reduces the probability of accidentally generating mainnet messages from your fid. 
2. it creates a testing ground for the contracts, which we need long term anyway.

**Comment by adityapk00** [comment]
We could deploy new contracts, but it will mean people will have to spend (testnet) gas to create FIDs to test. Will we need to build a UI for this?

From a code perspective, it is no different, so I'm not opposed to doing new contracts.

**Comment by varunsrin** [comment]
On further reflection, I think we should launch the first version of testnet with existing contracts. Its probably too much friction to ask developers to re-register fids in such a short timeframe. After this is done and mainnet is out we can "reclaunch" testnet with a separate set of contracts.
