### ISSUE TITLE
docs: write documentation to make it easier for developers to interact with hubs

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#589]
**What is the feature you would like to implement?**

See title

**Why is this feature important?**

Make it easier for developers to get started using Hubs. 

**Will the protocol spec need to be updated??**
No

**Comment by varunsrin** [comment]
Wrote the "fetch" tutorial [here](https://replit.com/@VarunSrinivasa4/Hub-Caller#index.js) which prints a simple reverse chron feed. A few issues: 

1. Endpoints have no pagination 
2. Endpoints return unsorted arrays while documentation indicates they're reverse chron
3. A simpler way to fetch fnames given an fid is necessary for a good developer experience

**Comment by varunsrin** [comment]
I played around with the documentation today putting myself in the place of a developer trying to build something with the Hubs. While @vinliao has done an amazing job with the TypeDocs setup, it is still far from usable to new developers. 

### Problems

Here's a few things that the current state of the documentation doesn't solve for:

- **I want to connect to a Hub with real data?** 
  - How do I get the IP address?
  - How do I authenticate to hubs during the private beta?
- **I want to read some data from the API's today**
   - Doesn't work, tutorial expects ethers v5 API's but the default npm install is v6
- **I want to write some data to the API's today**
   - No clear guidelines on how to create mentions or embeds or how they work. 
- **I want to subscribe to some data**
   - No guide on how subscribe works, what each of the return types mean
 - **I want to see what this API returns** 
   - Start [here](https://github.com/farcasterxyz/hubble/tree/main/packages/js) click around 6 levels deeps, and get an object whose response is spread across multiple pages
   
Besides that, its also generally hard to navigate and TypeDoc doesn't seem to start with the right default behaviors for us: 

- there is a file called [modules.md](https://github.com/farcasterxyz/hubble/blob/main/packages/js/docs/modules.md) that has an arbitrary selection of important documentatio 
- there is a folder called [modules](https://github.com/farcasterxyz/hubble/blob/main/packages/js/docs/modules/protobufs.md) that doesn't really seem related to modules.md
- there are two README.md files with mostly the same content
- Enum documentation is [excessively verbose](https://github.com/farcasterxyz/hubble/blob/main/packages/js/docs/enums/protobufs.HubEventType.md)
- Lacking documentation for [Client](https://github.com/farcasterxyz/hubble/blob/main/packages/js/docs/classes/Client.md)
- there is an interfaces folder with a ton of [hub related stuff](https://github.com/farcasterxyz/hubble/blob/main/packages/js/docs/interfaces/protobufs.AdminServiceServer.md) that isn't particularly useful to us. 

We'll need to step back and think about what the right documentation experience is for our users and work backwards from there, instead of relying on autogenerated defaults

**Comment by vinliao** [comment]
How do we feel about doing it like this (ignore the tables on the bottom half, it should've been deleted): https://github.com/vinliao/hubble/blob/b933e0c59b4d39f98b65200c6db7e3b67c95278c/packages/js/docs/Eip712Signer.md? That was made manually, but if we were to move to this format, it'd be mostly copy-pasting existing examples.

One idea to debloat the docs is to write it manually and put everything on the README (easier to `ctrl+f`). Manually writing docs means more maintenance cost, but we have full control over how the docs look.

**Comment by varunsrin** [comment]
Yeah, I'm going to take a pass over manually writing the docs because I think the automated versions have too many issuyes with the way TypeDoc does things.
