### ISSUE TITLE
chore: test coverage

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#59]
- [x] Implement coveralls/codecov for monitoring test coverage for every PR
- [x] Add test coverage requirements to PR merge checklist 
- [x] Do a final review of all uncovered lines before releasing 2.0.0

**Comment by varunsrin** [comment]
Coveralls was broken due to a permissions issue, fixed.

**Comment by pfletcherhill** [comment]
I'd be okay closing this issue and opening separate, more specific testing issues when they come up. My impression right now is that our unit testing coverage is adequate and we already have other issues for immediate integration tests (i.e. https://github.com/farcasterxyz/hubble/issues/588, https://github.com/farcasterxyz/hubble/issues/584)
