### ISSUE TITLE
feat: authentication for hubble endpoints

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hubble#606]
**What is the feature you would like to implement?**
Hubble gRPC endpoints should have some form of authentication to limit what clients can connect to them an post messages. 

**Why is this feature important?**
Hubble gRPC only authenticates peers, but not clients. A rogue or malfunctioning client could upload millions of messages to a Hubble instance and take it down for everyone. 

**Will the protocol spec need to be updated??**
No

**Comment by adityapk00** [comment]
So it looks like we can do grpc basic auth, but the username/password is sent on cleartext. We'll have to do SSL.

**Comment by adityapk00** [comment]
Done
