### ISSUE TITLE
error Command "identity" not found.

### ISSUE THREAD

**Issue by garysdevil** [farcasterxyz/hubble#642]
``yarn identity create # yarn identity create to create a network identity for your Hub``
```log
yarn run v1.22.19
error Command "identity" not found.
```

**Comment by varunsrin** [comment]
are you executing this from the apps/hubble folder?

**Comment by garysdevil** [comment]
> are you executing this from the apps/hubble folder?

Yeah, I didn't go into apps/hubble folder.
And I think we should update the README.md.

`` cd apps/hubble `` Navigate to this folder from the root
<img width="529" alt="image" src="https://user-images.githubusercontent.com/41293784/225225379-3ef468a0-bf29-4d09-9d36-5bbafa1d043e.png">

**Comment by varunsrin** [comment]
supportive of the change, lets close this issue for now
