### ISSUE TITLE
bug: label field on signers is required in Hubble but optional in Hub spec

### ISSUE THREAD

**Issue by gskril** [farcasterxyz/hubble#644]
**What is the bug?**
Label field on signers is optional according to the Farcaster Hub spec (discussed in https://github.com/farcasterxyz/protocol/pull/65 and https://github.com/farcasterxyz/hubble/issues/620) but required in Hubble packages (specifically [`packages/protobufs`](https://github.com/farcasterxyz/hubble/blob/main/packages/protobufs/src/generated/message.ts#L352)). 

It's not a critical issue for Hubble to be more strict than the protocol, but it caught my attention when working on a Hub indexer that uses some types from the Hubble packages so I wanted to make sure it's intentional.

**Comment by varunsrin** [comment]
good catch, will review.

**Comment by pfletcherhill** [comment]
@gskril can you share an example where signer `name` is required?
